/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./*.html', './src/**/*.{js,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#231a04',
        'secondary-fixed': '#ede1d0',
        'background': '#fcf9f8',
        'on-secondary': '#ffffff',
        'surface': '#fcf9f8',
        'primary-fixed': '#e5e2dc',
        'inverse-surface': '#303030',
        'on-tertiary-fixed-variant': '#514529',
        'on-secondary-container': '#6a6154',
        'on-surface': '#1b1c1c',
        'tertiary-fixed': '#f4e1ba',
        'primary': '#5f5e5a',
        'secondary': '#665d50',
        'secondary-container': '#eadecd',
        'on-tertiary': '#ffffff',
        'on-background': '#1b1c1c',
        'inverse-on-surface': '#f3f0f0',
        'primary-container': '#f7f4ee',
        'surface-container-highest': '#e4e2e1',
        'error': '#ba1a1a',
        'tertiary-fixed-dim': '#d7c5a0',
        'outline': '#787770',
        'inverse-primary': '#c9c6c1',
        'on-primary-container': '#706f6b',
        'surface-dim': '#dcd9d9',
        'on-primary': '#ffffff',
        'surface-container-high': '#eae7e7',
        'on-tertiary-container': '#7c6e4e',
        'on-primary-fixed': '#1c1c18',
        'surface-variant': '#e4e2e1',
        'on-error-container': '#93000a',
        'on-surface-variant': '#474741',
        'surface-container': '#f0eded',
        'surface-tint': '#5f5e5a',
        'on-secondary-fixed': '#201b10',
        'on-primary-fixed-variant': '#474743',
        'error-container': '#ffdad6',
        'tertiary': '#6a5d3f',
        'on-error': '#ffffff',
        'outline-variant': '#c8c7be',
        'on-secondary-fixed-variant': '#4d4639',
        'primary-fixed-dim': '#c9c6c1',
        'surface-container-low': '#f6f3f2',
        'surface-bright': '#fcf9f8',
        'secondary-fixed-dim': '#d0c5b5',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#fff3df',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        xl: '80px',
        sm: '12px',
        lg: '48px',
        md: '24px',
        base: '8px',
        'container-max': '1280px',
        'margin-mobile': '20px',
        xs: '4px',
        gutter: '24px',
      },
      fontFamily: {
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'editorial-italic': ['EB Garamond', 'serif'],
        'display-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-sm': ['13px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'editorial-italic': ['20px', { lineHeight: '1.4', fontWeight: '400' }],
        'display-lg-mobile': ['36px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
